### ISSUE TITLE
“Groups” need to change “그룹”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#1]
# Module: LAB_01-Manage_Entra_ID_Identities.md
#### Step: 00

Description of issue

“Groups” need to change “그룹”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/7de94342-9c3d-4d91-b052-b58ad7b3f07d)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
