### ISSUE TITLE
"애플리케이션 보안 그룹" need to change “Application security groups”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#10]
# Module: LAB_04-Implement_Virtual_Networking.md
#### Step: 00

Description of issue

"애플리케이션 보안 그룹" need to change “Application security groups”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/57d79107-2c68-4637-b8c6-38a41a54494b)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
