### ISSUE TITLE
"Service 태그" need to change “Service Tag”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#11]
# Module: LAB_04-Implement_Virtual_Networking.md
#### Step: 00

Description of issue

"Service 태그" need to change “Service Tag”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/b37239d8-67d0-4a9d-9a82-3013511c3412)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
