### ISSUE TITLE
"Private dns zones" need to change “프라이빗 DNS 영역” 

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#13]
# Module: LAB_04-Implement_Virtual_Networking.md
#### Step: 00

Description of issue

"Private dns zones" need to change “프라이빗 DNS 영역” 

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/077467e7-4719-4398-b585-ffc0283ce4ad)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
