### ISSUE TITLE
“가상 머신 기여자” need to change “가상 머신 참가자”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#3]
# Module: LAB_02a_Manage_Subscriptions_and_RBAC_Entra.md
#### Step: 00

Description of issue

“가상 머신 기여자” need to change “가상 머신 참가자”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/bfc7c393-615a-4a8e-a224-e5d52b3a0f38)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
