### ISSUE TITLE
"Create role assignment...." need to change “역할 할당 만들기”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#5]
# Module: LAB_02a_Manage_Subscriptions_and_RBAC_Entra.md
#### Step: 00

Description of issue
"Create role assignment...." need to change “역할 할당 만들기”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/5cfbad7b-af30-4e18-ac25-cd7720ba463c)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
