### ISSUE TITLE
"리소스에 대한 태그 및 해당 값 필요" need to change “Require a tag and its value on  resources”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#6]
# Module: LAB_02b-Manage_Governance_via_Azure_Policy.md
#### Step: 00

Description of issue
"리소스에 대한 태그 및 해당 값 필요" need to change “Require a tag and its value on  resources”
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/433cdefd-01c7-44cb-be69-c35bcd03b80d)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
