### ISSUE TITLE
"기본값이 포함된 비용 센터 태그 필요" need to change “Require a tag and its value on  resources”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#7]
# Module: LAB_02b-Manage_Governance_via_Azure_Policy.md
#### Step: 00

Description of issue
"기본값이 포함된 비용 센터 태그 필요" need to change “Require a tag and its value on  resources”
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/03df55a0-66c6-4038-9f0f-2baeb3d6cfcb)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
