### ISSUE TITLE
"Application security groups" need to change “애플리케이션 보안 그룹”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#8]
# Module: LAB_04-Implement_Virtual_Networking.md
#### Step: 00

Description of issue
"Application security groups" need to change “애플리케이션 보안 그룹”
![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/dda7e276-7b93-4932-a638-cedb67f3c816)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
