### ISSUE TITLE
"Network security groups" need to change “네트워크 보안 그룹”

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr#9]
# Module: LAB_04-Implement_Virtual_Networking.md
#### Step: 00

Description of issue

"Network security groups" need to change “네트워크 보안 그룹”

![image](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr/assets/24690076/a50e9b0e-ea4f-4b41-9b9f-c4d796e40e14)

Repro steps:

1.
1.
1.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team
